### ISSUE TITLE
Save-loop problem

### ISSUE THREAD

**Issue by zyrorl** [taichi/fix-onsave#1]
I find that when I try to save any javascript file that requires auto-fix it will break my file and go into a save-loop.

**Comment by philals** [comment]
Do you have save-on-focus lost set true?

**Comment by dsbert** [comment]
I had this same issue - I don't see any setting for save-on-focus but I do have `"files.autoSave": "off"` Also noticed that when this happened, I received an error from the ESLint plugin indicating a problem linting the file.

**Comment by taichi** [comment]
i fixed this problem. try new version.
